### ISSUE TITLE
Track cycles via `Runtime` instead of storage?

### ISSUE THREAD

**Issue by matklad** [nikomatsakis/salsa#2]
Currently, we detect cycles by storing `QueryState::InProgress` inside of `MemoizedStorage`.

I think this could be problematic for two reasons:

* we won't detect cycles for transparent queries
* if `MemoizedStorage` is shared by concurrently executing queries, we can get `CycleDetected` if two threads execute the same query simultaneously. 

I think that perhaps we need to move cycle tracking from storage to `Runtime`? The fix I have in mind is

* remove `QueryState` and use `map: RwLock<FxHashMap<Q::Key, Q::Value>>` in the storage,
* add `in_progress: FxHashSet<QC::QueryDescriptor>,` to `Runtime`, which stores the same info as `execution_stack`, but with an O(1) "contains" check.

**Comment by nikomatsakis** [comment]
Hmm, let's talk it through. I am not convinced yet that having a central "active query set" is a good idea, particularly in parallel.

Let me first sketch out what I had in mind for parallel execution. I had indeed planned to support queries executing in parallel -- and the framework is sort of *almost* there. As you pointed out, though, the cycle detection isn't quite right: you can't simply assume that just because a query is active there is a cycle. Instead, you have to look whether the active query is blocked on your request.  This gets more complex across threads.

My plan was to have a shared structure showing the dependencies between worker threads. If you see an active query, you check which thread it is active on: if it is the current thread, then you have a cycle.

Otherwise, you grab a lock and make your current thread depend on that other thread. In the process, you check that the other thread doesn't already depend on you (if it does, that's a cycle).  Presuming no cycle is detected, then you block until the result is ready and remove the dependency afterwards.

(I had planned to use a "scaling thread pool", that grows more threads as needed when things block.)

This is a bit different from what e.g. rustc is currently doing: it is instead just always blocking and then detecting when all workers have gone to sleep, which indicates deadlock. Deadlock indicates a cycle. I am not as keen on that approach, though it remains an option.

You can make this work with a central map, but I am wary, because it means more locks to juggle. We now have two maps to atomically "update" as we check for cycles and move queries from "inactive" to "active" state and so forth.

**Comment by nikomatsakis** [comment]
Regarding transparent queries (now called volatile), we could instead change their storage from being literally **nothing** to being just a set of active queries.

**Comment by matklad** [comment]
How would we deal with lock ordering issue? Suppose there are two top-level queries, X and Y, and two "atomic" queries A and B, such that X calls A and B, in that order, and Y calls B and A.

If we execute X and Y concurrently, we can get a deadlock.

**Comment by matklad** [comment]
Yep, tracking deps between threads seems to  be a good solution! More broadly, there are two ways of dealing with "query is executing by another thread" problem: we can either go ahead and recompute the value ourselves (because everything is deterministic and pure), or we could block on that other thread finishing the job. The second approach seems to require more machinery (you need to queue up waiting threads, and you need "scaling threadpool" to avoid deadlocks), but is more efficient.

**Comment by nikomatsakis** [comment]
> How would we deal with lock ordering issue? Suppose there are two top-level queries, X and Y, and two "atomic" queries A and B, such that X calls A and B, in that order, and Y calls B and A.

I don't know what locks you are talking about. Are you talking about locks internal to the runtime? I don't think there would be any issue — *while* a query is executing, we don't hold any locks, it's only for the duration of the lookup. So if query `X` is 

> we can either go ahead and recompute the value ourselves (because everything is deterministic and pure)

Yes, this is an option too, and an appealing one. Note though that sometimes there are side-effects -- e.g., in rustc, we report errors when we encounter them (we do however record the errors we report, so that the side effects are "known" — *almost* like a `Result`). Also, some queries can represent very large computations.

I think a good option would be something like this:

- Let queries be annotated in some way. I'm not sure what the default is, but it would let us choose between "block" or "execute a local copy".
- If we execute a local copy, we run it in a special mode where we forego caching and dependency tracking.

**Comment by nikomatsakis** [comment]
Maybe we should open an issue dedicated to the parallel design?

**Comment by nikomatsakis** [comment]
@matklad 

> we won't detect cycles for transparent queries

Are you interested in working on a PR to extend volatile (née transparent) queries so that they carry around a set of "active query descriptors", so that we can detect cycles with them?

(We should also write some tests of cycle detection, I realize...)

**Comment by matklad** [comment]
>Are you interested in working on a PR to extend volatile (née transparent) queries so that they carry around a set of "active query descriptors", so that we can detect cycles with them?

Sure! I'd **love** to do that, and I already have a couple of tests for this in a closed PR. 

Regarding tests, should we perhaps move them from the `examples` directory to `tests`? It's annoying to run `cargo test --example ...` from the command line (my "run test under cursor" deals with it, but running tests manually is also useful :))
